# Generated by Django 3.2.4 on 2023-02-12 02:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(default='UnTitled', max_length=200)),
                ('Number', models.IntegerField()),
                ('Food_Details', models.CharField(default='UnTitled', max_length=200)),
                ('Your_Address', models.CharField(default='UnTitled', max_length=200)),
                ('How_Much', models.CharField(default='UnTitled', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 12, 2, 39, 1, 176118, tzinfo=utc)),
        ),
    ]
