# Generated by Django 3.2.4 on 2023-02-12 03:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230212_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Food_Name',
            field=models.CharField(default='UnTitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 12, 3, 8, 0, 446091, tzinfo=utc)),
        ),
    ]
